name: 02 - Workflow Events

on:
  push:
  pull_request:
  schedule:
    # 02:10 UTC on Oct 18 (== 13:10 AEDT in Sydney on 2025-10-18)
    - cron: "10 2 18 10 *"
  workflow_dispatch:

jobs:
  echo-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Show timestamps
        run: |
          echo "event=${{ github.event_name }}"
          echo "utc:  $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          echo "syd:  $(TZ=Australia/Sydney date +'%Y-%m-%d %H:%M:%S %Z')"

      # Guard so it only DOES work on 2025-10-18 at/after 13:10 Sydney
      - name: Run only at/after 2025-10-18 13:10 Sydney
        run: |
          TARGET=$(TZ=Australia/Sydney date -d '2025-10-18 13:10:00' +%s)
          NOW=$(TZ=Australia/Sydney date +%s)
          echo "NOW_Sydney=$NOW  TARGET_Sydney=$TARGET"
          if [ "$NOW" -lt "$TARGET" ]; then
            echo "Not time yet — exiting without work."
            exit 0
          fi
          echo "✅ Target reached — proceeding."

      - name: show the trigger
        run: echo "I've been triggered by a(n) ${{ github.event_name }} event."
